### ISSUE TITLE
issues downloading the results of batch job

### ISSUE THREAD

**Issue by mbuchhorn** [Open-EO/openeo-geopyspark-driver#590]
job-id: 
j-2311167f76864f8ba91d15a2a2c185a0

Issues:
I can not download the data – again…..  not from the jupyter notebooks from which the job was started as well as not from the web-editor (see image)

![image](https://github.com/Open-EO/openeo-api/assets/125027391/a35e661b-80b1-46f4-9e86-1a4f5f2d355f)

**Comment by m-mohr** [comment]
Moved to openeo-geopyspark-driver

**Comment by tcassaert** [comment]
I got message from the WAF team that this is fixed. The download of the file now works for me, using the public endpoint.

@mbuchhorn could you confirm?

**Comment by mbuchhorn** [comment]
@tcassaert I still have issues. The processing is working but the download doesn't reach my drive. But I did got a different error message this time: [Errno 22] Invalid argument

Anyhow.... in my output folder I can see the file but it is only 0KB big.
job-id: j-2311222a91e744c5add4d6053fb690dd

**Comment by bossie** [comment]
I'm able to download your file Marcel.

What error does the following return?

```python
connection = openeo.connect("openeo.vito.be").authenticate_oidc()
connection.job("j-2311222a91e744c5add4d6053fb690dd").download_result("/tmp")
```

If there is a request ID (looks like "`ref: r-a0a3e3e0-3022-4d2c-bba2-02fa9e4411c9`") in the error, make sure to include it.

**Comment by mbuchhorn** [comment]
has worked now..... but it needed more than 45 minutes to retrieve the file :(
