### ISSUE TITLE
MultiEtlApiConfig warnings

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#773]
While looking at `openeogeotrellis.integrations.etl_api` logs I noticed quite a volume of these warnings:

> MultiEtlApiConfig: failed to get credentials for etl_url='https://marketplace-cost-api.example.com' (etl_id='foo') from cred_var='OPENEO_ETL_OIDC_CLIENT_CREDENTIALS_FOO_PROD': KeyError('OPENEO_ETL_OIDC_CLIENT_CREDENTIALS_FOO_PROD'). Skipping.

might be worth to give this a look

**Comment by soxofaan** [comment]
It happens from within batch jobs (which don't have these credential env vars set)

**Comment by jdries** [comment]
I think this has been solved in meantime, please reopen if not.

**Comment by soxofaan** [comment]
No this is still happening

see kibana `openeo-yarn-index-1m*` `name=openeogeotrellis.integrations.etl_api` `levelname=WARNING`

**Comment by soxofaan** [comment]
(still waiting successful CI build to verify on terrascope dev)
